#' Create twitter network graph with user information attributes
#'
#' Creates a network from the relations and users dataframes generated by Create. Network is supplemented with 
#' additional downloaded user information applied as node attributes.
#'
#' @param df_collect A dataframe containing the collected tweet data from \code{Collect}.
#' @param df_relations A dataframe containing the network relations data from \code{Create}.
#' @param df_users A dataframe containing the network users data from \code{Create}.
#' @param lookup_missing_users Logical. Request user information for any users missing from df_collect. Default 
#' is \code{TRUE}.
#' @param twitter_token An twitter authentication token from \code{Authenticate}.
#' @param writeToFile Logical. If \code{TRUE} a data frame of user information will be saved to file. Default 
#' is \code{FALSE}.
#' 
#' @return An igraph object of the twitter network with user node attributes.
#'
#' @export
GraphUserInfoTwitter <- function(df_collect, df_relations, df_users, lookup_missing_users = TRUE, 
                                 twitter_token = NULL, writeToFile = FALSE) {
  if (missing(lookup_missing_users)) {
    lookup_missing_users = FALSE
  }

  if (missing(writeToFile)) {
    writeToFile = FALSE
  }
  
  user_id <- NULL
  
  df_users_info <- rtweet::users_data(df_collect) %>% dplyr::distinct(user_id, .keep_all = TRUE)
  df_missing_users <- suppressWarnings(dplyr::anti_join(df_users, df_users_info, by = "user_id")) %>% 
    dplyr::distinct(user_id, .keep_all = TRUE)
  
  df_missing_users_info <- NULL
  if (lookup_missing_users) {
    if (missing(twitter_token) | is.null(twitter_token)) {
      cat("Please supply rtweet twitter authentication token to look up missing users info.\n")
    } else {
      # 90000 users per 15 mins with unused rate limit
      df_lookup_data <- rtweet::lookup_users(df_missing_users$user_id, parse = TRUE, 
                                             token = twitter_token$auth)
      df_missing_users_info <- rtweet::users_data(df_lookup_data)      
    }
  }
  
  if (!is.null(df_missing_users_info)) {
    df_users_info_all <- rbind(df_users_info, df_missing_users_info)
    
    if (writeToFile) {
      writeOutputFile(df_users_info_all, "rds", "TwitterUserInfo")
    }
  } else {
    df_users_info_all <- suppressWarnings(dplyr::bind_rows(df_users_info, df_missing_users))
  }
  
  df_users_info_all <- df_users_info_all %>% dplyr::rename("display_name" = .data$name, 
                                                           "name" = .data$user_id)
  g <- suppressWarnings(graph_from_data_frame(df_relations, directed = TRUE, vertices = df_users_info_all))
  V(g)$label <- V(g)$screen_name
  
  return(g)
}