#' @title Add columns of video information to network dataframes
#'
#' @description Network is supplemented with additional downloaded video information.
#'
#' @note Only supports twitter actor network at this time. Refer to \code{\link{AddUserData.actor.twitter}}.
#' 
#' @param net A named list of dataframes \code{nodes} and \code{edges} generated by \code{Create}.
#' @param data A dataframe generated by \code{Collect}.
#' @param ... Additional parameters passed to function.
#'
#' @return Network as a named list of two dataframes containing \code{$nodes} and \code{$edges}
#' including columns for additional video data.
#' 
#' @aliases AddVideoData
#' @name vosonSML::AddVideoData
#' @export
AddVideoData <- function(net, data, ...) {
  # searches the class list of net for matching method
  UseMethod("AddVideoData", net)
}

#' @noRd
#' @export
AddVideoData.default <- function(net, data, ...) {
  stop("Unknown network type passed to addvideodata.", call. = FALSE) 
}

#' @noRd
#' @method AddVideoData actor
#' @export
AddVideoData.actor <- function(net, ...) {
  
  UseMethod("AddVideoData.actor", net)
}

#' @noRd
#' @export
AddVideoData.actor.default <- function(net, ...) {
  stop("Unknown social media type passed to addvideodata.", call. = FALSE)
}

#' 
#' @aliases AddVideoData.actor.youtube
#' @name vosonSML::AddVideoData.actor.youtube
#' @export
AddVideoData.actor.youtube <- function(net, data, youtubeAuth = NULL, verbose = TRUE, ...) {
  
  func_output <- list(
    "nodes" = df_users_info_all,
    "edges" = net$edges
  )
  
  class(func_output) <- append(class(func_output), c("network", "actor", "twitter"))
  
  return(func_output)
}
